### ISSUE TITLE
.

### ISSUE THREAD

**Issue by pausad** [jflo846/grupparbete_buggrapport#7]

**Comment by jflo846** [comment]
Inloggad som lärare i wuma16, chrome och försökte ladda upp en zip-fil (10 mb) i en artikel.
Filen laddas upp men när sidan laddas om är den tom. 

![image](https://user-images.githubusercontent.com/55243015/65668270-b246ef00-e041-11e9-925b-b466208845d6.png)

När man klickar på förhandsgranska finns inte filen i artikeln. 

![image](https://user-images.githubusercontent.com/55243015/65668325-cc80cd00-e041-11e9-83b9-e5901149efec.png)
